- hosts: 'all_nodes' 
  become: true
  become_user: root
  vars:
    ansible_ssh_user: heat-admin
    rhnreg: False
  roles:
    - common

- hosts: '*control*' 
  become: true
  become_user: root
  vars:
    ansible_ssh_user: heat-admin
    rhnreg: False
  roles:
    - controller

