- name: restart neutron-server
  command: pcs resource restart neutron-server-clone
  run_once: true
  async: 300
  poll: 5
 
- name: restart neutron-lbaas-agent
  service: name=neutron-lbaas-agent.service state=restarted

- name: restart httpd
  command: pcs resource restart httpd-clone
  run_once: true
  async: 300
  poll: 5

