- name: Retrieving public ssh key
  set_fact:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- file:
    dest: '/root/.ssh'
    state: directory
    mode: 0700

- name: Ensure public_key is configured on root@undercloud
  lineinfile:
    line: "{{ ssh_pub_key }}"
    dest: /root/.ssh/authorized_keys
    create: yes
    state: present

