- name: Install RDO
  yum: name=python-rdomanager-oscplugin state=present

- name: Install some extra packages...
  yum: name={{ item }} state=present
  with_items:
          - screen
          - vim
            
- name: Install overcloud images (OSP8 only)
  yum: name={{ item }} state=present
  with_items:
          - python-tripleoclient
          - rhosp-director-images 
          - rhosp-director-images-ipa
  when: osp_version != "osp7"
