- include_vars: ../../../config.yaml
- include: pre-flight-checks.yaml
- include: set-hostname.yaml
- include: add-ssh-key-to-root.yaml
### - include: register-rhn.yaml
- include: create-stack-user.yaml 
- include: create-dirs.yaml
- include: modify-hosts.yaml
### - include: update-repos.yaml
- include: update-system.yaml
- include: reboot-system.yaml
- include: install-rdo.yaml
- include: bootif-fix.yaml
  when: bootifFix|default(false)|bool == true
- include: undercloud-config-ssl.yaml
- include: undercloud-config.yaml
- include: undercloud-install.yaml
- include: install-ansible.yaml
  when: goAnsible|default(false)|bool == true
- include: upload-playbooks.yaml
  when: goAnsible|default(false)|bool == true

